name: Arachni DAST Analysis

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  dast_analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install Backend Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r Backend/requirements.txt

      - name: Start Flask Application
        run: |
          python Backend/__init__.py &
          echo $! > flask_pid.txt
          sleep 10

      - name: Run Arachni Scanner
        run: |
          # Instalar dependencias necesarias para Arachni
          sudo apt update
          sudo apt install -y libcurl4 libxml2 libxslt-dev zlib1g-dev

          # Descargar Arachni
          curl -L https://github.com/Arachni/arachni/releases/download/v1.6.1.3/Arachni-1.6.1.3-0.6.1.1-linux-x86_64.tar.gz -o arachni.tar.gz

          # Verificar y descomprimir el archivo
          if file arachni.tar.gz | grep -q 'gzip compressed data'; then
              echo "Archivo válido, procediendo a descomprimir..."
              tar -xzf arachni.tar.gz
              extracted_dir=$(tar -tzf arachni.tar.gz | head -1 | cut -f1 -d"/")
              mv "$extracted_dir" arachni
          else
              echo "Error: El archivo descargado no es válido"
              exit 1
          fi

          # Ejecutar Arachni
          ./arachni/bin/arachni http://127.0.0.1:5000 --report-save-path=arachni_report.afr

      - name: Convert Arachni Report to HTML
        run: |
          ./arachni/bin/arachni_reporter arachni_report.afr --reporter=html:outfile=arachni_report.html

      - name: Upload Arachni Report
        uses: actions/upload-artifact@v3
        with:
          name: Arachni Security Report
          path: arachni_report.html

      - name: Stop Flask Application
        if: always()
        run: |
          kill $(cat flask_pid.txt)
